import { createReducer } from "../../../../utils/redux";

export const GET_ALL_USER_BELONG_TO_ROLE_SUCCESS = 'GET_ALL_USER_BELONG_TO_ROLE_SUCCESS';
export const GET_ALL_USER_BELONG_TO_ROLE_FAILED = 'GET_ALL_USER_BELONG_TO_ROLE_FAILED';
export const GET_ALL_USER_BELONG_TO_ROLE_CLEAR = 'GET_ALL_USER_BELONG_TO_ROLE_CLEAR';

export const getAllUserBelongToRoleResult = createReducer(
  GET_ALL_USER_BELONG_TO_ROLE_SUCCESS,
  GET_ALL_USER_BELONG_TO_ROLE_FAILED,
  GET_ALL_USER_BELONG_TO_ROLE_CLEAR
);