import { createReducer } from "../../../../utils/redux";

export const GET_ALL_CHANNEL_BY_SERVER_SUCCESS = 'GET_ALL_CHANNEL_BY_SERVER_SUCCESS';
export const GET_ALL_CHANNEL_BY_SERVER_FAILED = 'GET_ALL_CHANNEL_BY_SERVER_FAILED';
export const GET_ALL_CHANNEL_BY_SERVER_CLEAR = 'GET_ALL_CHANNEL_BY_SERVER_CLEAR';

export const getAllChannelByServerResult = createReducer(
  GET_ALL_CHANNEL_BY_SERVER_SUCCESS,
  GET_ALL_CHANNEL_BY_SERVER_FAILED,
  GET_ALL_CHANNEL_BY_SERVER_CLEAR
);