import { createReducer } from "../../../../utils/redux";

export const REMOVE_USER_FROM_SERVER_ROLE_SUCCESS = 'REMOVE_USER_FROM_SERVER_ROLE_SUCCESS';
export const REMOVE_USER_FROM_SERVER_ROLE_FAILED = 'REMOVE_USER_FROM_SERVER_ROLE_FAILED';
export const REMOVE_USER_FROM_SERVER_ROLE_CLEAR = 'REMOVE_USER_FROM_SERVER_ROLE_CLEAR';

export const removeUserFromServerRoleResult = createReducer(
  REMOVE_USER_FROM_SERVER_ROLE_SUCCESS,
  REMOVE_USER_FROM_SERVER_ROLE_FAILED,
  REMOVE_USER_FROM_SERVER_ROLE_CLEAR
);