import { createReducer } from "../../../../utils/redux";

export const GET_DETAIL_USER_ROLE_IN_SERVER_SUCCESS = 'GET_DETAIL_USER_ROLE_IN_SERVER_SUCCESS';
export const GET_DETAIL_USER_ROLE_IN_SERVER_FAILED = 'GET_DETAIL_USER_ROLE_IN_SERVER_FAILED';
export const GET_DETAIL_USER_ROLE_IN_SERVER_CLEAR = 'GET_DETAIL_USER_ROLE_IN_SERVER_CLEAR';

export const getDetailUserRoleInServerResult = createReducer(
  GET_DETAIL_USER_ROLE_IN_SERVER_SUCCESS,
  GET_DETAIL_USER_ROLE_IN_SERVER_FAILED,
  GET_DETAIL_USER_ROLE_IN_SERVER_CLEAR
);